name: flutter_warrior_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hexcolor: ^3.0.1
  get: ^4.6.6
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  #dio: ^5.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
